@c =============================================================
@c = 元 翻 訳: 高汐一紀＠電気通信大学
@c = 加筆修正: 大木敦雄＠大塚.筑波大学 = 1998/11/25
@c = emacs24jdoc を反映。 = 2013/11/10
@c =============================================================
@c This is part of the Emacs manual.
@c Copyright (C) 1985-1987, 1993-1995, 1997, 2001-2013 Free Software
@c Foundation, Inc.
@c See file emacs.texi for copying conditions.
@node M-x
@chapter 名前でコマンドを実行する方法

全ての Emacs コマンドには名前があり、それを使って実行することができます。
利便性のため、その多くにはキーバインディングもあります。
これらのコマンドはキーを打つことでも、名前を使っても実行することができます。
ほとんどの Emacs コマンドにはキーバインディングがありませんので、
それらを実行する唯一の方法は名前を使うことです。
(キーバインディングを設定する方法については、@xref{Key Bindings})

慣習として、コマンド名はハイフンで区切られた単語で成り立っています。
例えば、@code{auto-fill-mode} や @code{manual-entry} があります。
コマンド名はほとんどの場合、真っ当な英単語を使っているので、
覚えることは簡単です。

@kindex M-x
コマンドを名前で実行するには、@kbd{M-x} で始め、コマンド名を打って、
@key{RET} で終端します。@kbd{M-x} はミニバッファを使って、
コマンド名を受け取ります。文字列 @samp{M-x} がミニバッファの先頭に @dfn{プロンプト}
として表れ、ユーザに実行するコマンド名の入力を促します。
@key{RET} はミニバッファを抜けて、コマンドを実行します。
ミニバッファについて詳しくは、@xref{Minibuffer}。

コマンド名の入力には補完が使えます。
例えば、@code{forward-char} を呼び出すには、

@example
M-x forward-char @key{RET}
@end example

@noindent
あるいは、

@example
M-x forw @key{TAB} c @key{RET}
@end example

@noindent
@code{forward-char} は @kbd{C-f} と打って呼び出されるコマンドと同じものであることに注意してください。
キーバインディングがあるからといって、コマンドを名前で実行することが出来無くなるけではありません。

@kbd{M-x} を取り返してコマンドの実行を止めるには、コマンド名を入力するかわりに
@kbd{C-g} を打ちます。これでコマンドレベルに戻ります。

@kbd{M-x} で呼び出すつもりのコマンドに数引数を渡すには、
@kbd{M-x} よりも前に数引数を指定します。
引数の値はプロンプトに、コマンド名を受け取っている最中に表示され、
最後に @kbd{M-x} は引数をそのコマンドに渡します。

@vindex suggest-key-bindings
@kbd{M-x} で実行するコマンドにキーバインディングがある時は、
Emacs はコマンドを実行した後にこのことをエコー領域で通知します。
例えば、@kbd{M-x forward-word} と打つと、
@kbd{M-f} と打つとそのコマンドを実行できるというメッセージが現われます。
このメッセージを無効にするには、@code{suggest-key-bindings} 変数を @code{nil} に設定します。

このマニュアルでは、名前でコマンドを実行する場合、
名前を終端する @key{RET} をしばしば省略します。
つまり、@kbd{M-x auto-fill-mode @key{RET}} ではなく @kbd{M-x auto-fill-mode} と書く場合があります。
@key{RET} は、コマンドに引数が続くような場合に、強調する目的でだけ記載します。

@findex execute-extended-command
@kbd{M-x} は @code{execute-extended-command} コマンドを実行することで動作しています。
このコマンドが、別のコマンド名を受け取ってそれを呼び出す役割を担っています。
